name: deepglioma
channels:
  - conda-forge
dependencies:
  - numpy
  - pyyaml
  - pandas
  - matplotlib
  - tifffile
  - scikit-learn
  - scikit-image
  - opencv
  - pytorch
  - torchvision
  - openpyxl
  - vit-pytorch